// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: lesson/v1/lesson.proto

package lessonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lesson struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Teacher         *string                `protobuf:"bytes,4,opt,name=teacher,proto3,oneof" json:"teacher,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{0}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Lesson) GetTeacher() string {
	if x != nil && x.Teacher != nil {
		return *x.Teacher
	}
	return ""
}

func (x *Lesson) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *Lesson) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Lesson) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateLessonRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Teacher         *string                `protobuf:"bytes,3,opt,name=teacher,proto3,oneof" json:"teacher,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateLessonRequest) Reset() {
	*x = CreateLessonRequest{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonRequest) ProtoMessage() {}

func (x *CreateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLessonRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateLessonRequest) GetTeacher() string {
	if x != nil && x.Teacher != nil {
		return *x.Teacher
	}
	return ""
}

func (x *CreateLessonRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type CreateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonResponse) Reset() {
	*x = CreateLessonResponse{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonResponse) ProtoMessage() {}

func (x *CreateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonResponse.ProtoReflect.Descriptor instead.
func (*CreateLessonResponse) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type GetLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonRequest) Reset() {
	*x = GetLessonRequest{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonRequest) ProtoMessage() {}

func (x *GetLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonRequest.ProtoReflect.Descriptor instead.
func (*GetLessonRequest) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{3}
}

func (x *GetLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonResponse) Reset() {
	*x = GetLessonResponse{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonResponse) ProtoMessage() {}

func (x *GetLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonResponse.ProtoReflect.Descriptor instead.
func (*GetLessonResponse) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{4}
}

func (x *GetLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type ListLessonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLessonsRequest) Reset() {
	*x = ListLessonsRequest{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLessonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLessonsRequest) ProtoMessage() {}

func (x *ListLessonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLessonsRequest.ProtoReflect.Descriptor instead.
func (*ListLessonsRequest) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{5}
}

func (x *ListLessonsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLessonsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListLessonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       []*Lesson              `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLessonsResponse) Reset() {
	*x = ListLessonsResponse{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLessonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLessonsResponse) ProtoMessage() {}

func (x *ListLessonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLessonsResponse.ProtoReflect.Descriptor instead.
func (*ListLessonsResponse) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{6}
}

func (x *ListLessonsResponse) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *ListLessonsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateLessonRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Teacher         *string                `protobuf:"bytes,4,opt,name=teacher,proto3,oneof" json:"teacher,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateLessonRequest) Reset() {
	*x = UpdateLessonRequest{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonRequest) ProtoMessage() {}

func (x *UpdateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonRequest.ProtoReflect.Descriptor instead.
func (*UpdateLessonRequest) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLessonRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateLessonRequest) GetTeacher() string {
	if x != nil && x.Teacher != nil {
		return *x.Teacher
	}
	return ""
}

func (x *UpdateLessonRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type UpdateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonResponse) Reset() {
	*x = UpdateLessonResponse{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonResponse) ProtoMessage() {}

func (x *UpdateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonResponse.ProtoReflect.Descriptor instead.
func (*UpdateLessonResponse) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type DeleteLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonRequest) Reset() {
	*x = DeleteLessonRequest{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonRequest) ProtoMessage() {}

func (x *DeleteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonRequest.ProtoReflect.Descriptor instead.
func (*DeleteLessonRequest) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonResponse) Reset() {
	*x = DeleteLessonResponse{}
	mi := &file_lesson_v1_lesson_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonResponse) ProtoMessage() {}

func (x *DeleteLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_v1_lesson_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonResponse.ProtoReflect.Descriptor instead.
func (*DeleteLessonResponse) Descriptor() ([]byte, []int) {
	return file_lesson_v1_lesson_proto_rawDescGZIP(), []int{10}
}

var File_lesson_v1_lesson_proto protoreflect.FileDescriptor

const file_lesson_v1_lesson_proto_rawDesc = "" +
	"\n" +
	"\x16lesson/v1/lesson.proto\x12\tlesson.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x02\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\ateacher\x18\x04 \x01(\tH\x01R\ateacher\x88\x01\x01\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_teacher\"\xb8\x01\n" +
	"\x13CreateLessonRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\ateacher\x18\x03 \x01(\tH\x01R\ateacher\x88\x01\x01\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutesB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_teacher\"A\n" +
	"\x14CreateLessonResponse\x12)\n" +
	"\x06lesson\x18\x01 \x01(\v2\x11.lesson.v1.LessonR\x06lesson\"\"\n" +
	"\x10GetLessonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11GetLessonResponse\x12)\n" +
	"\x06lesson\x18\x01 \x01(\v2\x11.lesson.v1.LessonR\x06lesson\"P\n" +
	"\x12ListLessonsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"j\n" +
	"\x13ListLessonsResponse\x12+\n" +
	"\alessons\x18\x01 \x03(\v2\x11.lesson.v1.LessonR\alessons\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc8\x01\n" +
	"\x13UpdateLessonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\ateacher\x18\x04 \x01(\tH\x01R\ateacher\x88\x01\x01\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutesB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_teacher\"A\n" +
	"\x14UpdateLessonResponse\x12)\n" +
	"\x06lesson\x18\x01 \x01(\v2\x11.lesson.v1.LessonR\x06lesson\"%\n" +
	"\x13DeleteLessonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteLessonResponse2\x98\x03\n" +
	"\rLessonService\x12O\n" +
	"\fCreateLesson\x12\x1e.lesson.v1.CreateLessonRequest\x1a\x1f.lesson.v1.CreateLessonResponse\x12F\n" +
	"\tGetLesson\x12\x1b.lesson.v1.GetLessonRequest\x1a\x1c.lesson.v1.GetLessonResponse\x12L\n" +
	"\vListLessons\x12\x1d.lesson.v1.ListLessonsRequest\x1a\x1e.lesson.v1.ListLessonsResponse\x12O\n" +
	"\fUpdateLesson\x12\x1e.lesson.v1.UpdateLessonRequest\x1a\x1f.lesson.v1.UpdateLessonResponse\x12O\n" +
	"\fDeleteLesson\x12\x1e.lesson.v1.DeleteLessonRequest\x1a\x1f.lesson.v1.DeleteLessonResponseB7Z5github.com/eslsoft/lession/pkg/api/lesson/v1;lessonv1b\x06proto3"

var (
	file_lesson_v1_lesson_proto_rawDescOnce sync.Once
	file_lesson_v1_lesson_proto_rawDescData []byte
)

func file_lesson_v1_lesson_proto_rawDescGZIP() []byte {
	file_lesson_v1_lesson_proto_rawDescOnce.Do(func() {
		file_lesson_v1_lesson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lesson_v1_lesson_proto_rawDesc), len(file_lesson_v1_lesson_proto_rawDesc)))
	})
	return file_lesson_v1_lesson_proto_rawDescData
}

var file_lesson_v1_lesson_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_lesson_v1_lesson_proto_goTypes = []any{
	(*Lesson)(nil),                // 0: lesson.v1.Lesson
	(*CreateLessonRequest)(nil),   // 1: lesson.v1.CreateLessonRequest
	(*CreateLessonResponse)(nil),  // 2: lesson.v1.CreateLessonResponse
	(*GetLessonRequest)(nil),      // 3: lesson.v1.GetLessonRequest
	(*GetLessonResponse)(nil),     // 4: lesson.v1.GetLessonResponse
	(*ListLessonsRequest)(nil),    // 5: lesson.v1.ListLessonsRequest
	(*ListLessonsResponse)(nil),   // 6: lesson.v1.ListLessonsResponse
	(*UpdateLessonRequest)(nil),   // 7: lesson.v1.UpdateLessonRequest
	(*UpdateLessonResponse)(nil),  // 8: lesson.v1.UpdateLessonResponse
	(*DeleteLessonRequest)(nil),   // 9: lesson.v1.DeleteLessonRequest
	(*DeleteLessonResponse)(nil),  // 10: lesson.v1.DeleteLessonResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_lesson_v1_lesson_proto_depIdxs = []int32{
	11, // 0: lesson.v1.Lesson.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: lesson.v1.Lesson.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: lesson.v1.CreateLessonResponse.lesson:type_name -> lesson.v1.Lesson
	0,  // 3: lesson.v1.GetLessonResponse.lesson:type_name -> lesson.v1.Lesson
	0,  // 4: lesson.v1.ListLessonsResponse.lessons:type_name -> lesson.v1.Lesson
	0,  // 5: lesson.v1.UpdateLessonResponse.lesson:type_name -> lesson.v1.Lesson
	1,  // 6: lesson.v1.LessonService.CreateLesson:input_type -> lesson.v1.CreateLessonRequest
	3,  // 7: lesson.v1.LessonService.GetLesson:input_type -> lesson.v1.GetLessonRequest
	5,  // 8: lesson.v1.LessonService.ListLessons:input_type -> lesson.v1.ListLessonsRequest
	7,  // 9: lesson.v1.LessonService.UpdateLesson:input_type -> lesson.v1.UpdateLessonRequest
	9,  // 10: lesson.v1.LessonService.DeleteLesson:input_type -> lesson.v1.DeleteLessonRequest
	2,  // 11: lesson.v1.LessonService.CreateLesson:output_type -> lesson.v1.CreateLessonResponse
	4,  // 12: lesson.v1.LessonService.GetLesson:output_type -> lesson.v1.GetLessonResponse
	6,  // 13: lesson.v1.LessonService.ListLessons:output_type -> lesson.v1.ListLessonsResponse
	8,  // 14: lesson.v1.LessonService.UpdateLesson:output_type -> lesson.v1.UpdateLessonResponse
	10, // 15: lesson.v1.LessonService.DeleteLesson:output_type -> lesson.v1.DeleteLessonResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_lesson_v1_lesson_proto_init() }
func file_lesson_v1_lesson_proto_init() {
	if File_lesson_v1_lesson_proto != nil {
		return
	}
	file_lesson_v1_lesson_proto_msgTypes[0].OneofWrappers = []any{}
	file_lesson_v1_lesson_proto_msgTypes[1].OneofWrappers = []any{}
	file_lesson_v1_lesson_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lesson_v1_lesson_proto_rawDesc), len(file_lesson_v1_lesson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lesson_v1_lesson_proto_goTypes,
		DependencyIndexes: file_lesson_v1_lesson_proto_depIdxs,
		MessageInfos:      file_lesson_v1_lesson_proto_msgTypes,
	}.Build()
	File_lesson_v1_lesson_proto = out.File
	file_lesson_v1_lesson_proto_goTypes = nil
	file_lesson_v1_lesson_proto_depIdxs = nil
}
