// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: lession/v1/asset_service.proto

package lessionv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateAssetRequest applies partial updates to an asset.
type UpdateAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset contains the desired fields to update.
	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// update_mask indicates which fields in asset should be applied.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_lession_v1_asset_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_asset_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_asset_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateAssetRequest) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *UpdateAssetRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateAssetResponse returns the updated asset resource.
type UpdateAssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset is the persisted asset after the update.
	Asset         *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetResponse) Reset() {
	*x = UpdateAssetResponse{}
	mi := &file_lession_v1_asset_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetResponse) ProtoMessage() {}

func (x *UpdateAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_asset_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetResponse.ProtoReflect.Descriptor instead.
func (*UpdateAssetResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_asset_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAssetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

var File_lession_v1_asset_service_proto protoreflect.FileDescriptor

const file_lession_v1_asset_service_proto_rawDesc = "" +
	"\n" +
	"\x1elession/v1/asset_service.proto\x12\n" +
	"lession.v1\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\x1a\x16lession/v1/asset.proto\"\x82\x01\n" +
	"\x12UpdateAssetRequest\x12/\n" +
	"\x05asset\x18\x01 \x01(\v2\x11.lession.v1.AssetB\x06\xbaH\x03\xc8\x01\x01R\x05asset\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\">\n" +
	"\x13UpdateAssetResponse\x12'\n" +
	"\x05asset\x18\x01 \x01(\v2\x11.lession.v1.AssetR\x05asset2\xb8\x04\n" +
	"\fAssetService\x12Q\n" +
	"\fCreateUpload\x12\x1f.lession.v1.CreateUploadRequest\x1a .lession.v1.CreateUploadResponse\x12H\n" +
	"\tGetUpload\x12\x1c.lession.v1.GetUploadRequest\x1a\x1d.lession.v1.GetUploadResponse\x12W\n" +
	"\x0eCompleteUpload\x12!.lession.v1.CompleteUploadRequest\x1a\".lession.v1.CompleteUploadResponse\x12E\n" +
	"\bGetAsset\x12\x1b.lession.v1.GetAssetRequest\x1a\x1c.lession.v1.GetAssetResponse\x12K\n" +
	"\n" +
	"ListAssets\x12\x1d.lession.v1.ListAssetsRequest\x1a\x1e.lession.v1.ListAssetsResponse\x12N\n" +
	"\vUpdateAsset\x12\x1e.lession.v1.UpdateAssetRequest\x1a\x1f.lession.v1.UpdateAssetResponse\x12N\n" +
	"\vDeleteAsset\x12\x1e.lession.v1.DeleteAssetRequest\x1a\x1f.lession.v1.DeleteAssetResponseB9Z7github.com/eslsoft/lession/pkg/api/lession/v1;lessionv1b\x06proto3"

var (
	file_lession_v1_asset_service_proto_rawDescOnce sync.Once
	file_lession_v1_asset_service_proto_rawDescData []byte
)

func file_lession_v1_asset_service_proto_rawDescGZIP() []byte {
	file_lession_v1_asset_service_proto_rawDescOnce.Do(func() {
		file_lession_v1_asset_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lession_v1_asset_service_proto_rawDesc), len(file_lession_v1_asset_service_proto_rawDesc)))
	})
	return file_lession_v1_asset_service_proto_rawDescData
}

var file_lession_v1_asset_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lession_v1_asset_service_proto_goTypes = []any{
	(*UpdateAssetRequest)(nil),     // 0: lession.v1.UpdateAssetRequest
	(*UpdateAssetResponse)(nil),    // 1: lession.v1.UpdateAssetResponse
	(*Asset)(nil),                  // 2: lession.v1.Asset
	(*fieldmaskpb.FieldMask)(nil),  // 3: google.protobuf.FieldMask
	(*CreateUploadRequest)(nil),    // 4: lession.v1.CreateUploadRequest
	(*GetUploadRequest)(nil),       // 5: lession.v1.GetUploadRequest
	(*CompleteUploadRequest)(nil),  // 6: lession.v1.CompleteUploadRequest
	(*GetAssetRequest)(nil),        // 7: lession.v1.GetAssetRequest
	(*ListAssetsRequest)(nil),      // 8: lession.v1.ListAssetsRequest
	(*DeleteAssetRequest)(nil),     // 9: lession.v1.DeleteAssetRequest
	(*CreateUploadResponse)(nil),   // 10: lession.v1.CreateUploadResponse
	(*GetUploadResponse)(nil),      // 11: lession.v1.GetUploadResponse
	(*CompleteUploadResponse)(nil), // 12: lession.v1.CompleteUploadResponse
	(*GetAssetResponse)(nil),       // 13: lession.v1.GetAssetResponse
	(*ListAssetsResponse)(nil),     // 14: lession.v1.ListAssetsResponse
	(*DeleteAssetResponse)(nil),    // 15: lession.v1.DeleteAssetResponse
}
var file_lession_v1_asset_service_proto_depIdxs = []int32{
	2,  // 0: lession.v1.UpdateAssetRequest.asset:type_name -> lession.v1.Asset
	3,  // 1: lession.v1.UpdateAssetRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 2: lession.v1.UpdateAssetResponse.asset:type_name -> lession.v1.Asset
	4,  // 3: lession.v1.AssetService.CreateUpload:input_type -> lession.v1.CreateUploadRequest
	5,  // 4: lession.v1.AssetService.GetUpload:input_type -> lession.v1.GetUploadRequest
	6,  // 5: lession.v1.AssetService.CompleteUpload:input_type -> lession.v1.CompleteUploadRequest
	7,  // 6: lession.v1.AssetService.GetAsset:input_type -> lession.v1.GetAssetRequest
	8,  // 7: lession.v1.AssetService.ListAssets:input_type -> lession.v1.ListAssetsRequest
	0,  // 8: lession.v1.AssetService.UpdateAsset:input_type -> lession.v1.UpdateAssetRequest
	9,  // 9: lession.v1.AssetService.DeleteAsset:input_type -> lession.v1.DeleteAssetRequest
	10, // 10: lession.v1.AssetService.CreateUpload:output_type -> lession.v1.CreateUploadResponse
	11, // 11: lession.v1.AssetService.GetUpload:output_type -> lession.v1.GetUploadResponse
	12, // 12: lession.v1.AssetService.CompleteUpload:output_type -> lession.v1.CompleteUploadResponse
	13, // 13: lession.v1.AssetService.GetAsset:output_type -> lession.v1.GetAssetResponse
	14, // 14: lession.v1.AssetService.ListAssets:output_type -> lession.v1.ListAssetsResponse
	1,  // 15: lession.v1.AssetService.UpdateAsset:output_type -> lession.v1.UpdateAssetResponse
	15, // 16: lession.v1.AssetService.DeleteAsset:output_type -> lession.v1.DeleteAssetResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_lession_v1_asset_service_proto_init() }
func file_lession_v1_asset_service_proto_init() {
	if File_lession_v1_asset_service_proto != nil {
		return
	}
	file_lession_v1_asset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lession_v1_asset_service_proto_rawDesc), len(file_lession_v1_asset_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lession_v1_asset_service_proto_goTypes,
		DependencyIndexes: file_lession_v1_asset_service_proto_depIdxs,
		MessageInfos:      file_lession_v1_asset_service_proto_msgTypes,
	}.Build()
	File_lession_v1_asset_service_proto = out.File
	file_lession_v1_asset_service_proto_goTypes = nil
	file_lession_v1_asset_service_proto_depIdxs = nil
}
