// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: lession/v1/series_service.proto

package lessionv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListSeriesRequest carries filters for listing series.
type ListSeriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page_size limits the number of returned series.
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token continues a prior ListSeries response.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// statuses filters series by lifecycle state.
	Statuses []SeriesStatus `protobuf:"varint,3,rep,packed,name=statuses,proto3,enum=lession.v1.SeriesStatus" json:"statuses,omitempty"`
	// language filters series by primary locale.
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	// level filters series by difficulty level.
	Level string `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	// tags filters series that contain any of the supplied tags.
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// query performs a fuzzy match against titles and summaries.
	Query string `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	// include_episodes requests that episode details are embedded in the response.
	IncludeEpisodes bool `protobuf:"varint,8,opt,name=include_episodes,json=includeEpisodes,proto3" json:"include_episodes,omitempty"`
	// author_ids filters series that reference any of the supplied authors.
	AuthorIds     []string `protobuf:"bytes,9,rep,name=author_ids,json=authorIds,proto3" json:"author_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeriesRequest) Reset() {
	*x = ListSeriesRequest{}
	mi := &file_lession_v1_series_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeriesRequest) ProtoMessage() {}

func (x *ListSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeriesRequest.ProtoReflect.Descriptor instead.
func (*ListSeriesRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListSeriesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSeriesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSeriesRequest) GetStatuses() []SeriesStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListSeriesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListSeriesRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ListSeriesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListSeriesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListSeriesRequest) GetIncludeEpisodes() bool {
	if x != nil {
		return x.IncludeEpisodes
	}
	return false
}

func (x *ListSeriesRequest) GetAuthorIds() []string {
	if x != nil {
		return x.AuthorIds
	}
	return nil
}

// ListSeriesResponse returns a page of series.
type ListSeriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series contains the requested page of series resources.
	Series []*Series `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	// next_page_token is supplied when more data is available.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeriesResponse) Reset() {
	*x = ListSeriesResponse{}
	mi := &file_lession_v1_series_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeriesResponse) ProtoMessage() {}

func (x *ListSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeriesResponse.ProtoReflect.Descriptor instead.
func (*ListSeriesResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListSeriesResponse) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *ListSeriesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreateSeriesRequest supplies attributes for a new series.
type CreateSeriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series contains the desired attributes for the new series.
	Series        *SeriesDraft `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeriesRequest) Reset() {
	*x = CreateSeriesRequest{}
	mi := &file_lession_v1_series_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeriesRequest) ProtoMessage() {}

func (x *CreateSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeriesRequest.ProtoReflect.Descriptor instead.
func (*CreateSeriesRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSeriesRequest) GetSeries() *SeriesDraft {
	if x != nil {
		return x.Series
	}
	return nil
}

// CreateSeriesResponse returns the newly created series.
type CreateSeriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series is the persisted series with server-populated fields.
	Series        *Series `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeriesResponse) Reset() {
	*x = CreateSeriesResponse{}
	mi := &file_lession_v1_series_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeriesResponse) ProtoMessage() {}

func (x *CreateSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeriesResponse.ProtoReflect.Descriptor instead.
func (*CreateSeriesResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSeriesResponse) GetSeries() *Series {
	if x != nil {
		return x.Series
	}
	return nil
}

// GetSeriesRequest identifies the series to retrieve.
type GetSeriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series_id references the target series.
	SeriesId string `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	// include_episodes requests that episode details are embedded in the response.
	IncludeEpisodes bool `protobuf:"varint,2,opt,name=include_episodes,json=includeEpisodes,proto3" json:"include_episodes,omitempty"`
	// include_metadata requests that metadata is included when stored as a large payload.
	IncludeMetadata bool `protobuf:"varint,3,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSeriesRequest) Reset() {
	*x = GetSeriesRequest{}
	mi := &file_lession_v1_series_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesRequest) ProtoMessage() {}

func (x *GetSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetSeriesRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetSeriesRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *GetSeriesRequest) GetIncludeEpisodes() bool {
	if x != nil {
		return x.IncludeEpisodes
	}
	return false
}

func (x *GetSeriesRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

// GetSeriesResponse returns a single series resource.
type GetSeriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series is the requested resource.
	Series        *Series `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesResponse) Reset() {
	*x = GetSeriesResponse{}
	mi := &file_lession_v1_series_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesResponse) ProtoMessage() {}

func (x *GetSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetSeriesResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetSeriesResponse) GetSeries() *Series {
	if x != nil {
		return x.Series
	}
	return nil
}

// UpdateSeriesRequest applies a partial update to a series.
type UpdateSeriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series_id references the target series.
	SeriesId string `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	// series contains the fields to update.
	Series *SeriesDraft `protobuf:"bytes,2,opt,name=series,proto3" json:"series,omitempty"`
	// update_mask indicates which fields in series should be applied.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeriesRequest) Reset() {
	*x = UpdateSeriesRequest{}
	mi := &file_lession_v1_series_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeriesRequest) ProtoMessage() {}

func (x *UpdateSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeriesRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeriesRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSeriesRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *UpdateSeriesRequest) GetSeries() *SeriesDraft {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *UpdateSeriesRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateSeriesResponse returns the updated series resource.
type UpdateSeriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series is the persisted series after the update.
	Series        *Series `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeriesResponse) Reset() {
	*x = UpdateSeriesResponse{}
	mi := &file_lession_v1_series_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeriesResponse) ProtoMessage() {}

func (x *UpdateSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeriesResponse.ProtoReflect.Descriptor instead.
func (*UpdateSeriesResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSeriesResponse) GetSeries() *Series {
	if x != nil {
		return x.Series
	}
	return nil
}

// CreateEpisodeRequest supplies attributes for a new episode.
type CreateEpisodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// series_id references the parent series.
	SeriesId string `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	// episode contains the desired attributes for the new episode.
	Episode       *EpisodeDraft `protobuf:"bytes,2,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEpisodeRequest) Reset() {
	*x = CreateEpisodeRequest{}
	mi := &file_lession_v1_series_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEpisodeRequest) ProtoMessage() {}

func (x *CreateEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEpisodeRequest.ProtoReflect.Descriptor instead.
func (*CreateEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEpisodeRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *CreateEpisodeRequest) GetEpisode() *EpisodeDraft {
	if x != nil {
		return x.Episode
	}
	return nil
}

// CreateEpisodeResponse returns the newly created episode.
type CreateEpisodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// episode is the persisted episode with server-populated fields.
	Episode       *Episode `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEpisodeResponse) Reset() {
	*x = CreateEpisodeResponse{}
	mi := &file_lession_v1_series_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEpisodeResponse) ProtoMessage() {}

func (x *CreateEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEpisodeResponse.ProtoReflect.Descriptor instead.
func (*CreateEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateEpisodeResponse) GetEpisode() *Episode {
	if x != nil {
		return x.Episode
	}
	return nil
}

// GetEpisodeRequest identifies the episode to retrieve.
type GetEpisodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// episode_id references the target episode.
	EpisodeId     string `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpisodeRequest) Reset() {
	*x = GetEpisodeRequest{}
	mi := &file_lession_v1_series_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpisodeRequest) ProtoMessage() {}

func (x *GetEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpisodeRequest.ProtoReflect.Descriptor instead.
func (*GetEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetEpisodeRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

// GetEpisodeResponse returns a single episode resource.
type GetEpisodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// episode is the requested resource.
	Episode       *Episode `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpisodeResponse) Reset() {
	*x = GetEpisodeResponse{}
	mi := &file_lession_v1_series_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpisodeResponse) ProtoMessage() {}

func (x *GetEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpisodeResponse.ProtoReflect.Descriptor instead.
func (*GetEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetEpisodeResponse) GetEpisode() *Episode {
	if x != nil {
		return x.Episode
	}
	return nil
}

// UpdateEpisodeRequest applies a partial update to an episode.
type UpdateEpisodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// episode_id references the target episode.
	EpisodeId string `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	// episode contains the fields to update.
	Episode *EpisodeDraft `protobuf:"bytes,2,opt,name=episode,proto3" json:"episode,omitempty"`
	// update_mask indicates which fields in episode should be applied.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEpisodeRequest) Reset() {
	*x = UpdateEpisodeRequest{}
	mi := &file_lession_v1_series_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEpisodeRequest) ProtoMessage() {}

func (x *UpdateEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEpisodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEpisodeRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *UpdateEpisodeRequest) GetEpisode() *EpisodeDraft {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *UpdateEpisodeRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateEpisodeResponse returns the updated episode resource.
type UpdateEpisodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// episode is the persisted episode after the update.
	Episode       *Episode `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEpisodeResponse) Reset() {
	*x = UpdateEpisodeResponse{}
	mi := &file_lession_v1_series_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEpisodeResponse) ProtoMessage() {}

func (x *UpdateEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEpisodeResponse.ProtoReflect.Descriptor instead.
func (*UpdateEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateEpisodeResponse) GetEpisode() *Episode {
	if x != nil {
		return x.Episode
	}
	return nil
}

// DeleteEpisodeRequest performs a soft delete on an episode.
type DeleteEpisodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// episode_id references the target episode.
	EpisodeId     string `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEpisodeRequest) Reset() {
	*x = DeleteEpisodeRequest{}
	mi := &file_lession_v1_series_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEpisodeRequest) ProtoMessage() {}

func (x *DeleteEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEpisodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteEpisodeRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

// DeleteEpisodeResponse returns the archived episode.
type DeleteEpisodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// episode is the episode after it has been marked as deleted.
	Episode       *Episode `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEpisodeResponse) Reset() {
	*x = DeleteEpisodeResponse{}
	mi := &file_lession_v1_series_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEpisodeResponse) ProtoMessage() {}

func (x *DeleteEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lession_v1_series_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEpisodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_lession_v1_series_service_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteEpisodeResponse) GetEpisode() *Episode {
	if x != nil {
		return x.Episode
	}
	return nil
}

var File_lession_v1_series_service_proto protoreflect.FileDescriptor

const file_lession_v1_series_service_proto_rawDesc = "" +
	"\n" +
	"\x1flession/v1/series_service.proto\x12\n" +
	"lession.v1\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\x1a\x17lession/v1/series.proto\"\xfa\x02\n" +
	"\x11ListSeriesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12C\n" +
	"\bstatuses\x18\x03 \x03(\x0e2\x18.lession.v1.SeriesStatusB\r\xbaH\n" +
	"\x92\x01\a\"\x05\x82\x01\x02\x10\x01R\bstatuses\x123\n" +
	"\blanguage\x18\x04 \x01(\tB\x17\xbaH\x14\xd8\x01\x01r\x0f2\r^[a-zA-Z]{2}$R\blanguage\x12\x1d\n" +
	"\x05level\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x18@R\x05level\x12\"\n" +
	"\x04tags\x18\x06 \x03(\tB\x0e\xbaH\v\x92\x01\b\"\x06r\x04\x10\x01\x18@R\x04tags\x12\x14\n" +
	"\x05query\x18\a \x01(\tR\x05query\x12)\n" +
	"\x10include_episodes\x18\b \x01(\bR\x0fincludeEpisodes\x12+\n" +
	"\n" +
	"author_ids\x18\t \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\tauthorIds\"h\n" +
	"\x12ListSeriesResponse\x12*\n" +
	"\x06series\x18\x01 \x03(\v2\x12.lession.v1.SeriesR\x06series\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"N\n" +
	"\x13CreateSeriesRequest\x127\n" +
	"\x06series\x18\x01 \x01(\v2\x17.lession.v1.SeriesDraftB\x06\xbaH\x03\xc8\x01\x01R\x06series\"B\n" +
	"\x14CreateSeriesResponse\x12*\n" +
	"\x06series\x18\x01 \x01(\v2\x12.lession.v1.SeriesR\x06series\"\x8f\x01\n" +
	"\x10GetSeriesRequest\x12%\n" +
	"\tseries_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bseriesId\x12)\n" +
	"\x10include_episodes\x18\x02 \x01(\bR\x0fincludeEpisodes\x12)\n" +
	"\x10include_metadata\x18\x03 \x01(\bR\x0fincludeMetadata\"?\n" +
	"\x11GetSeriesResponse\x12*\n" +
	"\x06series\x18\x01 \x01(\v2\x12.lession.v1.SeriesR\x06series\"\xb2\x01\n" +
	"\x13UpdateSeriesRequest\x12%\n" +
	"\tseries_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bseriesId\x127\n" +
	"\x06series\x18\x02 \x01(\v2\x17.lession.v1.SeriesDraftB\x06\xbaH\x03\xc8\x01\x01R\x06series\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"B\n" +
	"\x14UpdateSeriesResponse\x12*\n" +
	"\x06series\x18\x01 \x01(\v2\x12.lession.v1.SeriesR\x06series\"y\n" +
	"\x14CreateEpisodeRequest\x12%\n" +
	"\tseries_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bseriesId\x12:\n" +
	"\aepisode\x18\x02 \x01(\v2\x18.lession.v1.EpisodeDraftB\x06\xbaH\x03\xc8\x01\x01R\aepisode\"F\n" +
	"\x15CreateEpisodeResponse\x12-\n" +
	"\aepisode\x18\x01 \x01(\v2\x13.lession.v1.EpisodeR\aepisode\"<\n" +
	"\x11GetEpisodeRequest\x12'\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tepisodeId\"C\n" +
	"\x12GetEpisodeResponse\x12-\n" +
	"\aepisode\x18\x01 \x01(\v2\x13.lession.v1.EpisodeR\aepisode\"\xb8\x01\n" +
	"\x14UpdateEpisodeRequest\x12'\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tepisodeId\x12:\n" +
	"\aepisode\x18\x02 \x01(\v2\x18.lession.v1.EpisodeDraftB\x06\xbaH\x03\xc8\x01\x01R\aepisode\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"F\n" +
	"\x15UpdateEpisodeResponse\x12-\n" +
	"\aepisode\x18\x01 \x01(\v2\x13.lession.v1.EpisodeR\aepisode\"?\n" +
	"\x14DeleteEpisodeRequest\x12'\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tepisodeId\"F\n" +
	"\x15DeleteEpisodeResponse\x12-\n" +
	"\aepisode\x18\x01 \x01(\v2\x13.lession.v1.EpisodeR\aepisode2\x9b\x05\n" +
	"\rSeriesService\x12K\n" +
	"\n" +
	"ListSeries\x12\x1d.lession.v1.ListSeriesRequest\x1a\x1e.lession.v1.ListSeriesResponse\x12Q\n" +
	"\fCreateSeries\x12\x1f.lession.v1.CreateSeriesRequest\x1a .lession.v1.CreateSeriesResponse\x12H\n" +
	"\tGetSeries\x12\x1c.lession.v1.GetSeriesRequest\x1a\x1d.lession.v1.GetSeriesResponse\x12Q\n" +
	"\fUpdateSeries\x12\x1f.lession.v1.UpdateSeriesRequest\x1a .lession.v1.UpdateSeriesResponse\x12T\n" +
	"\rCreateEpisode\x12 .lession.v1.CreateEpisodeRequest\x1a!.lession.v1.CreateEpisodeResponse\x12K\n" +
	"\n" +
	"GetEpisode\x12\x1d.lession.v1.GetEpisodeRequest\x1a\x1e.lession.v1.GetEpisodeResponse\x12T\n" +
	"\rUpdateEpisode\x12 .lession.v1.UpdateEpisodeRequest\x1a!.lession.v1.UpdateEpisodeResponse\x12T\n" +
	"\rDeleteEpisode\x12 .lession.v1.DeleteEpisodeRequest\x1a!.lession.v1.DeleteEpisodeResponseB9Z7github.com/eslsoft/lession/pkg/api/lession/v1;lessionv1b\x06proto3"

var (
	file_lession_v1_series_service_proto_rawDescOnce sync.Once
	file_lession_v1_series_service_proto_rawDescData []byte
)

func file_lession_v1_series_service_proto_rawDescGZIP() []byte {
	file_lession_v1_series_service_proto_rawDescOnce.Do(func() {
		file_lession_v1_series_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lession_v1_series_service_proto_rawDesc), len(file_lession_v1_series_service_proto_rawDesc)))
	})
	return file_lession_v1_series_service_proto_rawDescData
}

var file_lession_v1_series_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_lession_v1_series_service_proto_goTypes = []any{
	(*ListSeriesRequest)(nil),     // 0: lession.v1.ListSeriesRequest
	(*ListSeriesResponse)(nil),    // 1: lession.v1.ListSeriesResponse
	(*CreateSeriesRequest)(nil),   // 2: lession.v1.CreateSeriesRequest
	(*CreateSeriesResponse)(nil),  // 3: lession.v1.CreateSeriesResponse
	(*GetSeriesRequest)(nil),      // 4: lession.v1.GetSeriesRequest
	(*GetSeriesResponse)(nil),     // 5: lession.v1.GetSeriesResponse
	(*UpdateSeriesRequest)(nil),   // 6: lession.v1.UpdateSeriesRequest
	(*UpdateSeriesResponse)(nil),  // 7: lession.v1.UpdateSeriesResponse
	(*CreateEpisodeRequest)(nil),  // 8: lession.v1.CreateEpisodeRequest
	(*CreateEpisodeResponse)(nil), // 9: lession.v1.CreateEpisodeResponse
	(*GetEpisodeRequest)(nil),     // 10: lession.v1.GetEpisodeRequest
	(*GetEpisodeResponse)(nil),    // 11: lession.v1.GetEpisodeResponse
	(*UpdateEpisodeRequest)(nil),  // 12: lession.v1.UpdateEpisodeRequest
	(*UpdateEpisodeResponse)(nil), // 13: lession.v1.UpdateEpisodeResponse
	(*DeleteEpisodeRequest)(nil),  // 14: lession.v1.DeleteEpisodeRequest
	(*DeleteEpisodeResponse)(nil), // 15: lession.v1.DeleteEpisodeResponse
	(SeriesStatus)(0),             // 16: lession.v1.SeriesStatus
	(*Series)(nil),                // 17: lession.v1.Series
	(*SeriesDraft)(nil),           // 18: lession.v1.SeriesDraft
	(*fieldmaskpb.FieldMask)(nil), // 19: google.protobuf.FieldMask
	(*EpisodeDraft)(nil),          // 20: lession.v1.EpisodeDraft
	(*Episode)(nil),               // 21: lession.v1.Episode
}
var file_lession_v1_series_service_proto_depIdxs = []int32{
	16, // 0: lession.v1.ListSeriesRequest.statuses:type_name -> lession.v1.SeriesStatus
	17, // 1: lession.v1.ListSeriesResponse.series:type_name -> lession.v1.Series
	18, // 2: lession.v1.CreateSeriesRequest.series:type_name -> lession.v1.SeriesDraft
	17, // 3: lession.v1.CreateSeriesResponse.series:type_name -> lession.v1.Series
	17, // 4: lession.v1.GetSeriesResponse.series:type_name -> lession.v1.Series
	18, // 5: lession.v1.UpdateSeriesRequest.series:type_name -> lession.v1.SeriesDraft
	19, // 6: lession.v1.UpdateSeriesRequest.update_mask:type_name -> google.protobuf.FieldMask
	17, // 7: lession.v1.UpdateSeriesResponse.series:type_name -> lession.v1.Series
	20, // 8: lession.v1.CreateEpisodeRequest.episode:type_name -> lession.v1.EpisodeDraft
	21, // 9: lession.v1.CreateEpisodeResponse.episode:type_name -> lession.v1.Episode
	21, // 10: lession.v1.GetEpisodeResponse.episode:type_name -> lession.v1.Episode
	20, // 11: lession.v1.UpdateEpisodeRequest.episode:type_name -> lession.v1.EpisodeDraft
	19, // 12: lession.v1.UpdateEpisodeRequest.update_mask:type_name -> google.protobuf.FieldMask
	21, // 13: lession.v1.UpdateEpisodeResponse.episode:type_name -> lession.v1.Episode
	21, // 14: lession.v1.DeleteEpisodeResponse.episode:type_name -> lession.v1.Episode
	0,  // 15: lession.v1.SeriesService.ListSeries:input_type -> lession.v1.ListSeriesRequest
	2,  // 16: lession.v1.SeriesService.CreateSeries:input_type -> lession.v1.CreateSeriesRequest
	4,  // 17: lession.v1.SeriesService.GetSeries:input_type -> lession.v1.GetSeriesRequest
	6,  // 18: lession.v1.SeriesService.UpdateSeries:input_type -> lession.v1.UpdateSeriesRequest
	8,  // 19: lession.v1.SeriesService.CreateEpisode:input_type -> lession.v1.CreateEpisodeRequest
	10, // 20: lession.v1.SeriesService.GetEpisode:input_type -> lession.v1.GetEpisodeRequest
	12, // 21: lession.v1.SeriesService.UpdateEpisode:input_type -> lession.v1.UpdateEpisodeRequest
	14, // 22: lession.v1.SeriesService.DeleteEpisode:input_type -> lession.v1.DeleteEpisodeRequest
	1,  // 23: lession.v1.SeriesService.ListSeries:output_type -> lession.v1.ListSeriesResponse
	3,  // 24: lession.v1.SeriesService.CreateSeries:output_type -> lession.v1.CreateSeriesResponse
	5,  // 25: lession.v1.SeriesService.GetSeries:output_type -> lession.v1.GetSeriesResponse
	7,  // 26: lession.v1.SeriesService.UpdateSeries:output_type -> lession.v1.UpdateSeriesResponse
	9,  // 27: lession.v1.SeriesService.CreateEpisode:output_type -> lession.v1.CreateEpisodeResponse
	11, // 28: lession.v1.SeriesService.GetEpisode:output_type -> lession.v1.GetEpisodeResponse
	13, // 29: lession.v1.SeriesService.UpdateEpisode:output_type -> lession.v1.UpdateEpisodeResponse
	15, // 30: lession.v1.SeriesService.DeleteEpisode:output_type -> lession.v1.DeleteEpisodeResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_lession_v1_series_service_proto_init() }
func file_lession_v1_series_service_proto_init() {
	if File_lession_v1_series_service_proto != nil {
		return
	}
	file_lession_v1_series_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lession_v1_series_service_proto_rawDesc), len(file_lession_v1_series_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lession_v1_series_service_proto_goTypes,
		DependencyIndexes: file_lession_v1_series_service_proto_depIdxs,
		MessageInfos:      file_lession_v1_series_service_proto_msgTypes,
	}.Build()
	File_lession_v1_series_service_proto = out.File
	file_lession_v1_series_service_proto_goTypes = nil
	file_lession_v1_series_service_proto_depIdxs = nil
}
